env:
 - CMAKE_VERSION_MAJOR=3.5
 - CMAKE_VERSION=3.5.2
language: c++
os:
- osx
env:
- CTEST_MODEL=Experimental
compiler:
- clang
before_script:
- env
- echo ${CMAKE_VERSION}
- cmake --version
- clang --version
- mkdir /Users/travis/build/QIICR/dcmqi-build
- cd /Users/travis/build/QIICR
- wget --no-check-certificate https://cmake.org/files/v${CMAKE_VERSION_MAJOR}/cmake-${CMAKE_VERSION}.tar.gz
- tar zxf cmake-${CMAKE_VERSION}.tar.gz
- mv cmake-${CMAKE_VERSION} cmake-build
- cd cmake-build
- ./configure && make
script:
- cd /Users/travis/build/QIICR/dcmqi-build
- /Users/travis/build/QIICR/cmake-build/bin/cmake /Users/travis/build/QIICR/dcmqi
- make
- cd /Users/travis/build/QIICR/dcmqi-build/dcmqi-build && /Users/travis/build/QIICR/cmake-build/bin/ctest -VV -DCTEST_MODEL=$CTEST_MODEL -DCTEST_EMPTY_BINARY_DIRECTORY=FALSE .
