name: C/C++ CI Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 
  build-windows:
    
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '17'
          msbuild-architecture: x64
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.0'
      
      - name: Download prerequisite packages
        run: |
          $client = new-object System.Net.WebClient;
          $client.DownloadFile("https://github.com/QIICR/dicom3tools/releases/download/20200512090031/dicom3tools_winexe_1.00.snapshot.20200512090031.zip", "${{ github.workspace }}\dicom3tools.zip")
          $client.DownloadFile("https://github.com/QIICR/zlib-dcmqi/releases/download/zlib-dcmqi-1.2.3-VS17-Win64-Release-static/zlib-dcmqi.zip", "${{ github.workspace }}\zlib-dcmqi.zip")
          $client.DownloadFile("https://github.com/QIICR/dcmtk-dcmqi/releases/download/DCMTK-dcmqi-3.6.7_20220105-VS12-Win64-Release-v0.0.32-static/DCMTK-dcmqi.zip", "${{ github.workspace }}\DCMTK-dcmqi.zip")
          $client.DownloadFile("https://github.com/QIICR/ITK-dcmqi/releases/download/ITK-dcmqi-VS17-Win64-Release-v0.0.40-static/ITK-dcmqi.zip", "${{ github.workspace }}\ITK-dcmqi.zip")
        shell: pwsh

      - name: Uncompress prerequisite packages
        run: |
          7z x ${{ github.workspace }}\dicom3tools.zip -o${{ github.workspace }}\dicom3tools
          7z x ${{ github.workspace }}\zlib-dcmqi.zip  -o${{ github.workspace }}\zlib-install
          7z x ${{ github.workspace }}\DCMTK-dcmqi.zip -o${{ github.workspace }}\DCMTK-install
          7z x ${{ github.workspace }}\ITK-dcmqi.zip   -o${{ github.workspace }}\ITK-install

      - name: Install prerequisite python packages
        run: |
          pip install -U "scikit-ci-addons>=0.18.0"
          pip install jsondiff
          
      - name: Configure project

        run: |
          ls ${{ github.workspace }}
          echo "WORKSPACE dir: ${{ github.workspace }}"
          cmake --version
          mkdir ${{ github.workspace }}\dcmqi-build
          echo "Step 2"
          cd ${{ github.workspace }}\dcmqi-build
          echo "Step 3"
          cmake -G "Visual Studio 17 2022" -Ax64 -DITK_DIR:PATH=${{ github.workspace }}\ITK-install\lib\cmake\ITK-5.3 -DDCMTK_DIR:PATH=${{ github.workspace }}\DCMTK-install\cmake -DZLIB_ROOT:PATH=${{ github.workspace }}\zlib-install -DZLIB_INCLUDE_DIR:PATH=${{ github.workspace }}\zlib-install\include -DZLIB_LIBRARY:FILEPATH=${{ github.workspace }}\zlib-install\lib\zlib.lib -DBUILD_SHARED_LIBS:BOOL=OFF ${{ github.workspace }}

      - name: Build and package
        run: |
          cmake --build . --config Release -- /m
          cd ${{ github.workspace }}\dcmqi-build\dcmqi-build
          cmake --build . --config Release --target PACKAGE -- /m
      
      
      
